learning_task: "transductive"
device: "cuda"
parallel: 1
runs: 1
loss: "mse"
accuracy: "r_squared"
datasets:
  - data:
        dataset: "chameleon"
        data_split: [ 0.2 ,0.3 ]
        unlabelled: 0.0
  - data:
      dataset: "squirrel"
      data_split: [ 0.2 ,0.3 ]
      unlabelled: 0.0
  - data:
      dataset: "crocodile"
      data_split: [ 0.2 ,0.3 ]
      unlabelled: 0.0
models:
  - model:
      model_name: "gcn"
      adjacency: "mlp"
      epochs: 300
      nonlinearity: "relu"
      batchnorm: Yes
      batch_size: 1
      layers: 2
      hidden: 32
      dropout: 0.5
      concat: No
      optimizer:
        optimizer_name: "adam"
        lr: 0.1
  - model:
      model_name: "gcn"
      adjacency: "mlp"
      epochs: 300
      nonlinearity: "sigmoid"
      batchnorm: Yes
      batch_size: 1
      layers: 2
      hidden: 32
      dropout: 0.5
      concat: No
      optimizer:
        optimizer_name: "adam"
        lr: 0.1



