learning_task: "inductive_clustering"
runs: 1 # only one run metrics are aggregated across kmeans runs not across experiments
data:
  dataset: "reddit-binary"
  feature_dim: 128
  data_split: [0.2, 0.1]
  unlabelled: 0.0
model:
  model_name: "gae"
  encoder: "gcn"
  adjacency: "welling-normalized"
  epochs: 200
  dropout: 0.5
  hidden: 32
  embedding_topk: 320
  batch_size: 8
  optimizer:
    optimizer_name: "adam"
    lr: 0.0001




